services:
  postgres:
    image: postgres:17-alpine
    container_name: webpolls-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - webpolls-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webpolls-backend
    ports:
      - "8080:8080"
    networks:
      - webpolls-network
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: postgres
      DB_PORT: 5432
    restart: unless-stopped

networks:
  webpolls-network:
    driver: bridge
