// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Option struct {
	ID      int32        `json:"id"`
	Content string       `json:"content"`
	PollID  int32        `json:"poll_id"`
	Correct sql.NullBool `json:"correct"`
}

type Poll struct {
	ID     int32  `json:"id"`
	Title  string `json:"title"`
	UserID int32  `json:"user_id"`
}

type User struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}
