// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: options.sql

package db

import (
	"context"
)

const createOption = `-- name: CreateOption :one
INSERT INTO options (content, poll_id)
VALUES ($1, $2)
RETURNING id, content, poll_id
`

type CreateOptionParams struct {
	Content string `json:"content"`
	PollID  int32  `json:"poll_id"`
}

func (q *Queries) CreateOption(ctx context.Context, arg CreateOptionParams) (Option, error) {
	row := q.db.QueryRow(ctx, createOption, arg.Content, arg.PollID)
	var i Option
	err := row.Scan(&i.ID, &i.Content, &i.PollID)
	return i, err
}

const deleteOption = `-- name: DeleteOption :exec
DELETE FROM options
WHERE id = $1
`

func (q *Queries) DeleteOption(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteOption, id)
	return err
}

const getAllOptions = `-- name: GetAllOptions :many
SELECT id, content, poll_id
FROM options
ORDER BY id ASC
`

func (q *Queries) GetAllOptions(ctx context.Context) ([]Option, error) {
	rows, err := q.db.Query(ctx, getAllOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Option
	for rows.Next() {
		var i Option
		if err := rows.Scan(&i.ID, &i.Content, &i.PollID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOptionByID = `-- name: GetOptionByID :one
SELECT id, content, poll_id
FROM options
WHERE id = $1
`

func (q *Queries) GetOptionByID(ctx context.Context, id int32) (Option, error) {
	row := q.db.QueryRow(ctx, getOptionByID, id)
	var i Option
	err := row.Scan(&i.ID, &i.Content, &i.PollID)
	return i, err
}

const getOptionByPollID = `-- name: GetOptionByPollID :many
SELECT id, content, poll_id
FROM options
WHERE poll_id = $1
ORDER BY id ASC
`

func (q *Queries) GetOptionByPollID(ctx context.Context, pollID int32) ([]Option, error) {
	rows, err := q.db.Query(ctx, getOptionByPollID, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Option
	for rows.Next() {
		var i Option
		if err := rows.Scan(&i.ID, &i.Content, &i.PollID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOption = `-- name: UpdateOption :one
UPDATE options
SET content = $1
WHERE id = $2
RETURNING id, content, poll_id
`

type UpdateOptionParams struct {
	Content string `json:"content"`
	ID      int32  `json:"id"`
}

func (q *Queries) UpdateOption(ctx context.Context, arg UpdateOptionParams) (Option, error) {
	row := q.db.QueryRow(ctx, updateOption, arg.Content, arg.ID)
	var i Option
	err := row.Scan(&i.ID, &i.Content, &i.PollID)
	return i, err
}
