// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: polls.sql

package db

import (
	"context"
)

const createPoll = `-- name: CreatePoll :one
INSERT INTO polls (title, user_id)
VALUES ($1, $2)
RETURNING title, user_id
`

type CreatePollParams struct {
	Title  string `json:"title"`
	UserID int32  `json:"user_id"`
}

type CreatePollRow struct {
	Title  string `json:"title"`
	UserID int32  `json:"user_id"`
}

func (q *Queries) CreatePoll(ctx context.Context, arg CreatePollParams) (CreatePollRow, error) {
	row := q.db.QueryRowContext(ctx, createPoll, arg.Title, arg.UserID)
	var i CreatePollRow
	err := row.Scan(&i.Title, &i.UserID)
	return i, err
}

const deletePoll = `-- name: DeletePoll :exec
DELETE FROM polls
WHERE id = $1
`

func (q *Queries) DeletePoll(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePoll, id)
	return err
}

const getAllPolls = `-- name: GetAllPolls :many
SELECT title, user_id
FROM polls
`

type GetAllPollsRow struct {
	Title  string `json:"title"`
	UserID int32  `json:"user_id"`
}

func (q *Queries) GetAllPolls(ctx context.Context) ([]GetAllPollsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPolls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPollsRow
	for rows.Next() {
		var i GetAllPollsRow
		if err := rows.Scan(&i.Title, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPollByID = `-- name: GetPollByID :one
SELECT title, user_id
FROM polls
WHERE id = $1
`

type GetPollByIDRow struct {
	Title  string `json:"title"`
	UserID int32  `json:"user_id"`
}

func (q *Queries) GetPollByID(ctx context.Context, id int32) (GetPollByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPollByID, id)
	var i GetPollByIDRow
	err := row.Scan(&i.Title, &i.UserID)
	return i, err
}

const updatePoll = `-- name: UpdatePoll :exec
UPDATE polls
SET title = $2
WHERE id = $1
`

type UpdatePollParams struct {
	ID    int32  `json:"id"`
	Title string `json:"title"`
}

func (q *Queries) UpdatePoll(ctx context.Context, arg UpdatePollParams) error {
	_, err := q.db.ExecContext(ctx, updatePoll, arg.ID, arg.Title)
	return err
}
