// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: polls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPoll = `-- name: CreatePoll :one
INSERT INTO polls (title, user_id)
VALUES ($1, $2)
RETURNING id,title, user_id
`

type CreatePollParams struct {
	Title  string `json:"title"`
	UserID int32  `json:"user_id"`
}

func (q *Queries) CreatePoll(ctx context.Context, arg CreatePollParams) (Poll, error) {
	row := q.db.QueryRow(ctx, createPoll, arg.Title, arg.UserID)
	var i Poll
	err := row.Scan(&i.ID, &i.Title, &i.UserID)
	return i, err
}

const deletePoll = `-- name: DeletePoll :exec
DELETE FROM polls
WHERE id = $1
`

func (q *Queries) DeletePoll(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deletePoll, id)
	return err
}

const getAllPolls = `-- name: GetAllPolls :many
SELECT
    p.id AS poll_id,
    p.title,
    p.user_id,
    o.id AS option_id,
    o.content AS option_content,
    r.option_id AS user_voted_option_id
FROM polls p
JOIN options o ON p.id = o.poll_id
LEFT JOIN results r ON p.id = r.poll_id AND r.user_id = $1
ORDER BY p.id ASC
`

type GetAllPollsRow struct {
	PollID            int32       `json:"poll_id"`
	Title             string      `json:"title"`
	UserID            int32       `json:"user_id"`
	OptionID          int32       `json:"option_id"`
	OptionContent     string      `json:"option_content"`
	UserVotedOptionID pgtype.Int4 `json:"user_voted_option_id"`
}

func (q *Queries) GetAllPolls(ctx context.Context, userID int32) ([]GetAllPollsRow, error) {
	rows, err := q.db.Query(ctx, getAllPolls, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPollsRow
	for rows.Next() {
		var i GetAllPollsRow
		if err := rows.Scan(
			&i.PollID,
			&i.Title,
			&i.UserID,
			&i.OptionID,
			&i.OptionContent,
			&i.UserVotedOptionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPollByID = `-- name: GetPollByID :many
SELECT 
    polls.id,
    polls.title,
    polls.user_id,
    options.id AS option_id,
    options.content AS option_content
FROM polls
inner JOIN options ON polls.id = options.poll_id
WHERE polls.id = $1
ORDER BY polls.id ASC
`

type GetPollByIDRow struct {
	ID            int32  `json:"id"`
	Title         string `json:"title"`
	UserID        int32  `json:"user_id"`
	OptionID      int32  `json:"option_id"`
	OptionContent string `json:"option_content"`
}

func (q *Queries) GetPollByID(ctx context.Context, id int32) ([]GetPollByIDRow, error) {
	rows, err := q.db.Query(ctx, getPollByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPollByIDRow
	for rows.Next() {
		var i GetPollByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.UserID,
			&i.OptionID,
			&i.OptionContent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPollsByUserID = `-- name: GetPollsByUserID :many
SELECT
    p.id AS poll_id,
    p.title,
    p.user_id,
    o.id AS option_id,
    o.content AS option_content,
    r.option_id AS user_voted_option_id
FROM polls p
JOIN options o ON p.id = o.poll_id
LEFT JOIN results r ON p.id = r.poll_id AND r.user_id = $1
WHERE p.user_id = $2
ORDER BY p.id ASC
`

type GetPollsByUserIDParams struct {
	ViewerID int32 `json:"viewer_id"`
	OwnerID  int32 `json:"owner_id"`
}

type GetPollsByUserIDRow struct {
	PollID            int32       `json:"poll_id"`
	Title             string      `json:"title"`
	UserID            int32       `json:"user_id"`
	OptionID          int32       `json:"option_id"`
	OptionContent     string      `json:"option_content"`
	UserVotedOptionID pgtype.Int4 `json:"user_voted_option_id"`
}

func (q *Queries) GetPollsByUserID(ctx context.Context, arg GetPollsByUserIDParams) ([]GetPollsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getPollsByUserID, arg.ViewerID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPollsByUserIDRow
	for rows.Next() {
		var i GetPollsByUserIDRow
		if err := rows.Scan(
			&i.PollID,
			&i.Title,
			&i.UserID,
			&i.OptionID,
			&i.OptionContent,
			&i.UserVotedOptionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePoll = `-- name: UpdatePoll :exec
UPDATE polls
SET title = $1
WHERE id = $2
`

type UpdatePollParams struct {
	Title string `json:"title"`
	ID    int32  `json:"id"`
}

func (q *Queries) UpdatePoll(ctx context.Context, arg UpdatePollParams) error {
	_, err := q.db.Exec(ctx, updatePoll, arg.Title, arg.ID)
	return err
}
